[build]
     command = "npm run build"
     publish = "dist"

   [[redirects]]
     from = "/api/*"
     to = "/.netlify/functions/:splat"
     status = 200

   [[headers]]
     for = "/icons/ge/*"
     [headers.values]
       Cache-Control = "public, max-age=31536000, immutable"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200

   [functions."osrs-news-cache"]
   schedule = "*/10 * * * *"

   [functions."jmod-comments-cache"]
   schedule = "*/10 * * * *"

   [functions."ge-prices-cache"]
   schedule = "*/1 * * * *"
